application/views.py
from flask import Blueprint, render_template, abort
from flask_jwt_extended import get_jwt_identity

from application import db
from application.models import Annotation, UserAnnotation, AppUser

from sqlalchemy import func, and_

from . import view_require_level, view_require_role

main_bp = Blueprint("main", __name__)

@main_bp.route("/")
def login():
	return render_template("login.html")

@main_bp.route("/review")
@view_require_role("annotator")
def tagging():
	return render_template("tagging.html")
	
@main_bp.route("/review/<tid>")
@view_require_role("annotator")
def tagging_specific(tid):
	return render_template("tagging.html", specific_tid=tid)

@main_bp.route("/check_ua")
@view_require_role("auto-annotator")
def review_ua():
	return render_template("review_ua.html")

@main_bp.route("/validate_ua")
@view_require_role("all")
def validate_ua():
	return render_template("review_ua.html", validate=1)

@main_bp.route("/search")
@view_require_role("annotator")
def search():
	return render_template("search.html")

@main_bp.route("/annotate")
@view_require_role("annotator")
def rank_tagging():
	return render_template("ranktagging.html")

@main_bp.route("/myprofile")
@view_require_level(1)
def myprofile():
	username = get_jwt_identity()
	appuser = AppUser.query.filter_by(username=username).scalar()

	maximum_timestamps = db.session.query(Annotation.tweet_id, 
		Annotation.appuser_id, func.max(Annotation.timestamp).label("timestamp")
		).group_by(Annotation.tweet_id).subquery()
	annotations = db.session.query(Annotation).filter_by(appuser_id=appuser.id).join(maximum_timestamps, and_(
		maximum_timestamps.c.tweet_id == Annotation.tweet_id,
			maximum_timestamps.c.timestamp == Annotation.timestamp
		)).order_by(Annotation.timestamp.desc()).all()
	
	nonempty_annotations = list(filter(lambda a: not a.is_empty(), annotations))

	maximum_timestamps = db.session.query(UserAnnotation.user_id, 
			UserAnnotation.appuser_id, func.max(UserAnnotation.timestamp).label("timestamp")
			).group_by(UserAnnotation.user_id).subquery()
	uannotations = db.session.query(UserAnnotation).filter_by(reviewed_by=appuser.id, reviewed=True).join(maximum_timestamps, and_(
		maximum_timestamps.c.user_id == UserAnnotation.user_id,
			maximum_timestamps.c.timestamp == UserAnnotation.timestamp
		)).count()
	
	stats = {"total": len(nonempty_annotations), "total_auto": uannotations}


	return render_template("myprofile.html", user=appuser.__dict__, annotations=[a.tweet_id for a in annotations[:100]], stats=stats)

@main_bp.route("/stats")
@view_require_level(3)
def stats():
	return render_template("stats.html")

@main_bp.route("/signup")
def signup():
	return render_template("signup.html")

@main_bp.route("/video-tagging")
@view_require_role("video-annotator")
def videotagging():
	video = "debatea5noviembre"
	return render_template("video-tagging.html", video=video)

@main_bp.route("/phpinfo")
def teapot():
	abort(418)

@main_bp.route("/workertest")
def workertest():
	worker = Worker.query.filter_by(name="test").first or Worker("test", AQUITASK)
	return worker.result if worker.job_finished else worker()

application/templates/createbatch.html
{% set active_page = "createbatch" %}
<!DOCTYPE html>
<html>
	<head>
		<link rel="shortcut icon" type="image/x-icon" href="{{ url_for('static', filename='favicon.ico') }}" />
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
		<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
		<link href="{{ static_autoversion('css/main.css') }}" rel="stylesheet">
		<title>Nutcracker Tagging</title>
	</head>
	<body class="{{ config['REVERSE_PROXY_PATH'].strip('/') }}">
		<div class="container-fluid">
			<div class="row">
				<div class="col-md-10 offset-md-1 col-xl-10 offset-xl-1 order-first" id="errorcol">
					{% with messages = get_flashed_messages() %}
						{% if messages %}
						<div class="mt-4 alert alert-danger" id="errormessage">
							<i class="fa fa-exclamation-triangle" aria-hidden="true"></i> Something went wrong :(<br />
							{% for message in messages %}
								{{ message }}<br />
							{% endfor %}
						</div>
						{% endif %}
					{% endwith %}
				</div>
			</div>
			<div class="row">
				<div class="col-md-10 offset-md-1 col-xl-10 offset-xl-1 order-xl-1 mt-4 h-100">
					<form role="form" id="batchform">
						<label for="batch">Enter JSON formatted list of Tweets:</label>
						<textarea name="batch" id="batch" class="form-control" style="min-height:500px"></textarea>
					</form>
				</div>
 
				
				<div class="col-md-10 offset-md-1 col-xl-10 offset-xl-1 order-first mt-4">
					<nav class="navbar navbar-dark bg-dark navbar-expand-xl justify-content-between">
						<a class="navbar-brand">
							<img src="{{ url_for('static', filename='images/logo.png') }}" width="30" height="30" class="d-inline-block align-top" alt="">
							Nutcracker Tagging
						</a>
						<div class="collapse navbar-collapse" id="navbarContent">
							{% include "menu.partial.html" %}
						</div>
						<button type="button" class="btn btn-primary" id="uploadbutton">Upload Batch</button>
					</nav>
				</div>
				
			</div>
			<div class="row bg-dark text-light footer mt-4 p-4">
				<div class="col-md-3 offset-md-1 text-right d-flex align-items-center justify-content-center">
					<img src="{{ url_for('static', filename='images/ugrnegativo.png') }}" width="80%" class="d-inline-block align-top" alt="">
				</div>
				<div class="col-md-7 d-flex flex-column justify-content-center">
					<span class="text-light">This is the Nutcracker app from University of Granada. The use of this system is strictly restricted to members of the Nutcracker project and we may monitor your interactions and transmissions to ensure it. We may use cookies. Accessing the website without the proper authorisation is prohibited. You explicitly accepted this disclaimer when logging in.</span>
					<span class="text-light mt-1">This work has been financially supported by the Spanish Ministry of Economy and Competitiveness (MINECO), project FFI2016-79748-R, and cofinancied by the European Social Fund (ESF). The author was supported by the FPI 2017 predoctoral programme, from the Spanish Ministry of Economy and Competitiveness (MINECO), grant number BES-2017-081202.</span>
					<span class="text-light mt-2">If you encounter any problems when using this site, please, contact Manuel Francisco &lt;francisco@decsai.ugr.es&gt; for support.</span>
				</div>
			</div>
		</div>
		<script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/js-cookie@beta/dist/js.cookie.min.js"></script>
		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
		<script src="{{ static_autoversion('js/batch.js') }}"></script>
	</body>
</html>

application/templates/login.html
{% set active_page = "login" %}
<!DOCTYPE html>
<html>
	<head>
		<link rel="shortcut icon" type="image/x-icon" href="{{ url_for('static', filename='favicon.ico') }}" />
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
		<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
		<link href="{{ static_autoversion('css/main.css') }}" rel="stylesheet">
		<title>Nutcracker</title>
		<style>
			html, body {
				min-height: 100%;
				height: 100%;
			}
			
			body {
				background: black url("{{ url_for('static', filename='images/fondo.jpg') }}") no-repeat center;
				background-size: cover;
			}
			
			.transparent-card {
				background-color: rgba(255, 255, 255, .9) !important;
			}
		</style>
	</head>
	<body>
		<div class="container h-100">
			<div class="row h-100">
				<div class="col-sm-12 col-md-10 col-lg-7 mx-auto my-auto">
					<div class="card transparent-card shadow rounded">
						<div class="card-body" id="cardbody">
							{% with messages = get_flashed_messages() %}
								{% if messages %}
								<div class="alert alert-danger" id="errormessage">
									<i class="fa fa-exclamation-triangle" aria-hidden="true"></i> Something went wrong :(<br />
									{% for message in messages %}
										{{ message }}<br />
									{% endfor %}
								</div>
								{% endif %}
							{% endwith %}
							<h5 class="card-title text-center">Nutcracker - Log In</h5>
							<h6 class="card-subtitle text-center"><a href="/english">English Tweets</a> / <a href="/">Spanish Tweets</a> / <a href="/arabic">Arabic Tweets</a> / <a href="/madrid">Telemadrid Tweets</a></h6>
							<h6 id="web_version"></h6>
							<form class="text-center" id="loginform">
								<div class="form-group text-left">
									<label for="username">Username</label>
									<input type="text" class="form-control form-control-lg mb-2" placeholder="Enter your username" id="username" name="username">
									<label for="password">Password</label>
									<input type="password" class="form-control form-control-lg mb-2" placeholder="Enter your password" id="password" name="password" autocomplete="on">
								</div>
								<p class="card-text text-secondary">If you do not have an account, click <a href="{{ url_for('main.signup') }}">here to sign up</a>.<br />If you have forgotten your password, you need to contact support in order to set a new one.</p>
								<p class="card-text text-secondary">This is the Nutcracker app from University of Granada. The use of this system is strictly restricted to members of the Nutcracker project and we may monitor your interactions and transmissions to ensure it. We may use cookies. Accessing the website without the proper authorisation is prohibited. You explicitly accept this disclaimer when logging in.</p>
								<button type="submit" class="btn btn-lg btn-primary" id="loginbutton">Log In</button>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
		<script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/js-cookie@beta/dist/js.cookie.min.js"></script>
		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
		<script src="{{ static_autoversion('js/login.js') }}"></script>
		<script>
			$(function()
			{
				if (window.location.href.indexOf("/english") > -1)
					$("#web_version").html("Current version: English tweets").css({"text-align": "center", "margin-top": "15px", "font-weight": "bold"});
				else if (window.location.href.indexOf("/arabic") > -1)
					$("#web_version").html("Current version: Arabic tweets").css({"text-align": "center", "margin-top": "15px", "font-weight": "bold"});
				else if (window.location.href.indexOf("/madrid") > -1)
					$("#web_version").html("Current version: Debate Telemadrid 2021").css({"text-align": "center", "margin-top": "15px", "font-weight": "bold"});
				else
					$("#web_version").html("Current version: Debate a 5 RTVE 2019").css({"text-align": "center", "margin-top": "15px", "font-weight": "bold"});
			});
		</script>
	</body>
</html>

application/templates/menu.partial.html
{% set navigation_bar = [
    (url_for('main.rank_tagging'), "ranktagging", "Annotate"),
    (url_for('main.tagging'), "tagging", "Review"),
    (url_for('main.review_ua'), "review_ua", "Auto-annotations"),
    (url_for('main.videotagging'), "video-tagging", "Video-Annotation"),
    (url_for('main.search'), "search", "Search"),
    (url_for('main.myprofile'), "myprofile", "My Profile"),
    (url_for('main.stats'), "stats", "Stats"),
] -%}

<ul class="navbar-nav mr-auto">
    {% for href, id, caption in navigation_bar %}
    <li class="nav-item">
        <a class="nav-link{% if id == active_page %} active{% endif %}" href="{{ href|e }}">{{ caption|e }}</a>
    </li>
    {% endfor %}
</ul>

application/templates/myprofile.html
{% set active_page = "myprofile" %}
<!DOCTYPE html>
<html class="h-100">
	<head>
		<link rel="shortcut icon" type="image/x-icon" href="{{ url_for('static', filename='favicon.ico') }}" />
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
		<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
		<link href="{{ static_autoversion('css/main.css') }}" rel="stylesheet">
		<title>Nutcracker Tagging</title>
	</head>
	<body class="h-100 {{ config['REVERSE_PROXY_PATH'].strip('/') }}">
		<div class="container-fluid" style="min-height: 100%">
			<div class="row">
				<div class="col-xl-10 offset-xl-1 mt-4">
					<nav class="navbar navbar-dark navbar-expand-xl bg-dark justify-content-between">
						<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
							<span class="navbar-toggler-icon"></span>
						</button>
						<a class="navbar-brand">
							<img src="{{ url_for('static', filename='images/logo.png') }}" width="30" height="30" id="logo" class="d-inline-block align-top" alt="">
							Nutcracker Tagging
						</a>
						<div class="collapse navbar-collapse" id="navbarContent">
							{% include "menu.partial.html" %}
						</div>
					</nav>
				</div>
				<div class="col-xl-10 offset-xl-1 mt-4">
					{% with messages = get_flashed_messages() %}
						{% if messages %}
						<div class="mt-4 alert alert-danger" id="errormessage">
							<i class="fa fa-exclamation-triangle" aria-hidden="true"></i> Something went wrong :(<br />
							{% for message in messages %}
								{{ message }}<br />
							{% endfor %}
						</div>
						{% endif %}
					{% endwith %}
				</div>
			</div>
			<div class="row">
				<div class="col-xl-10 offset-xl-1">
					<div class="row mainrow">
						<!-- Main Column -->
						<div class="col">
							<div class="media p-3 border border-secondary rounded">
								<div class="media-body">
									<h4 class="card-title">Welcome back, <strong>{{ user.username }}</strong>!</h4>
									<h5 class="mt-0">Your details</h5>
									<span class="card-text"><strong>Name: </strong> {{ user.name }}</span><br />
									<span class="card-text"><strong>Email: </strong> {{ user.email }}</span><br />
									<span class="card-text"><strong>No. tweets annotated: </strong> {{ stats["total"] }}</span><br />
									<span class="card-text"><strong>No. auto-annotations revised: </strong> {{ stats["total_auto"] }}</span><br />
									<h5 class="mt-4">Your last 100 annotations</h5>
									<p>	
										{% for tweet in annotations %}
										<a href="{{ url_for('main.tagging') }}/{{ tweet }}" alt="Review tweet {{ tweet }}">{{ tweet }}</a>&nbsp;
										{% endfor %}
									</p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="row bg-dark text-light footer mt-4 p-4">
				<div class="col-md-3 offset-md-1 text-right d-flex align-items-center justify-content-center">
					<img src="{{ url_for('static', filename='images/ugrnegativo.png') }}" width="80%" class="d-inline-block align-top" alt="">
				</div>
				<div class="col-md-7 d-flex flex-column justify-content-center">
					<span class="text-light">This is the Nutcracker app from University of Granada. The use of this system is strictly restricted to members of the Nutcracker project and we may monitor your interactions and transmissions to ensure it. We may use cookies. Accessing the website without the proper authorisation is prohibited. You explicitly accepted this disclaimer when logging in.</span>
					<span class="text-light mt-1">This work has been financially supported by the Spanish Ministry of Economy and Competitiveness (MINECO), project FFI2016-79748-R, and cofinancied by the European Social Fund (ESF). The author was supported by the FPI 2017 predoctoral programme, from the Spanish Ministry of Economy and Competitiveness (MINECO), grant number BES-2017-081202.</span>
					<span class="text-light mt-2">If you encounter any problems when using this site, please, contact Manuel Francisco &lt;francisco@decsai.ugr.es&gt; for support.</span>
				</div>
			</div>
		</div>
		<script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/js-cookie@beta/dist/js.cookie.min.js"></script>
		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
		<script src="{{ url_for('static', filename='js/jquery.hotkeys.js') }}"></script>
		<script src="{{ static_autoversion('js/myprofile.js') }}"></script>
	</body>
</html>

application/templates/review_ua.html
{% set active_page = "review_ua" %}
<!DOCTYPE html>
<html>
	<head>
		<link rel="shortcut icon" type="image/x-icon" href="{{ url_for('static', filename='favicon.ico') }}" />
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
		<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
		<link href="{{ static_autoversion(filename='css/main.css') }}" rel="stylesheet">
		<title>Nutcracker Tagging</title>
	</head>
	<body class="{{ config['REVERSE_PROXY_PATH'].strip('/') }}">
		<div class="container-fluid">
			<div class="row">
				<div class="col-xl-10 offset-xl-1 mt-4">
					<nav class="navbar navbar-dark navbar-expand-xl bg-dark justify-content-between">
						<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
							<span class="navbar-toggler-icon"></span>
						</button>
						<a class="navbar-brand">
							<img src="{{ url_for('static', filename='images/logo.png') }}" width="30" height="30" id="logo" class="d-inline-block align-top" alt="">
							Nutcracker Tagging
						</a>
						<div class="collapse navbar-collapse" id="navbarContent">
							{% include "menu.partial.html" %}
						</div>
						<div class="form-inline">
							<div class="btn-group mr-auto">
								<button type="button" class="btn btn-secondary btn-sm" id="firstunlabelled">Resume Work</button>
								<button type="button" class="btn btn-primary btn-sm" id="revisit">Revisit UID</button>
							</div>
							
							<div class="input-group input-group-sm">
								<label for="page" class="sr-only">UID: </label>
								<div class="input-group-prepend">
									<div class="input-group-text">UID</div>
								</div>
								<input type="number" class="form-control form-control-sm" style="width:100px" id="page" name="page" min="1">
							</div>
						</div>
					</nav>
				</div>
				<div class="col-xl-10 offset-xl-1 mt-4">
					{% with messages = get_flashed_messages() %}
						{% if messages %}
						<div class="mt-4 alert alert-danger" id="errormessage">
							<i class="fa fa-exclamation-triangle" aria-hidden="true"></i> Something went wrong :(<br />
							{% for message in messages %}
								{{ message }}<br />
							{% endfor %}
						</div>
						{% endif %}
					{% endwith %}
				</div>
			</div>
			<div class="row">
				<div class="col-xl-10 offset-xl-1">
					<div class="row">
						<div class="col">
							<!--<div class="media p-3 border border-secondary rounded mb-4" id="keyboard_shortcuts">
								<div class="media-body">
									<h6 class="mt-0 text-secondary">Keyboard Shortcuts</h6>
									<span class="keyboard-key">n</span> Definetely wrong<br />
									<span class="keyboard-key">y</span> Seems right<br />
									<span class="keyboard-key">j</span> Neutral (cannot confirm or deny)<br />
									<span class="keyboard-key">h</span> toggle this dialog<br />
									<div class="mt-4 d-none" id="spanishDiagram">
										<img src="{{ url_for('static', filename='images/diagrama.png') }}" class="diagram" alt="">
									</div>
									<div class="mt-4 d-none" id="englishDiagram">
										<img src="{{ url_for('static', filename='images/diagram.png') }}" class="diagram" alt="">
									</div>
								</div>
							</div>-->
						</div>
					</div>
					<div class="row mainrow">
						<div class="col mt-4" id="ua_list">
							
						</div>
					</div>
				</div>
			</div>
			<div class="row bg-dark text-light footer mt-4 p-4">
				<div class="col-md-3 offset-md-1 text-right d-flex align-items-center justify-content-center">
					<img src="{{ url_for('static', filename='images/ugrnegativo.png') }}" width="80%" class="d-inline-block align-top" alt="">
				</div>
				<div class="col-md-7 d-flex flex-column justify-content-center">
					<span class="text-light">This is the Nutcracker app from University of Granada. The use of this system is strictly restricted to members of the Nutcracker project and we may monitor your interactions and transmissions to ensure it. We may use cookies. Accessing the website without the proper authorisation is prohibited. You explicitly accepted this disclaimer when logging in.</span>
					<span class="text-light mt-1">This work has been financially supported by the Spanish Ministry of Economy and Competitiveness (MINECO), project FFI2016-79748-R, and cofinancied by the European Social Fund (ESF). The author was supported by the FPI 2017 predoctoral programme, from the Spanish Ministry of Economy and Competitiveness (MINECO), grant number BES-2017-081202.</span>
					<span class="text-light mt-2">If you encounter any problems when using this site, please, contact Manuel Francisco &lt;francisco@decsai.ugr.es&gt; for support.</span>
				</div>
			</div>
		</div>
		<script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/js-cookie@beta/dist/js.cookie.min.js"></script>
		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
		<script src="{{ url_for('static', filename='js/jquery.hotkeys.js') }}"></script>
		<script>
			var validate = {{ validate if validate else 0 }};
		</script>
		<script src="{{ static_autoversion('js/review_ua.js') }}"></script>
	</body>
</html>